# Site settings
title: My (Simple) Website
author:
  name: Joseph Guillermo Pinete Hnath
  email: josephhnath@g.harvard.edu
description: "simple website that I am working on updating"

# Build settings
remote_theme: jekyll/cayman
